using Xunit;

// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Generated at 2016-03-20 15:13:06Z
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace NickBuhro.NumToWords.Tests.Russian
{
	partial class RussianConverterTests
	{
		[Fact]
		public void Masculine0Test()
		{
			var number = 0;
			var expected = "ноль";
			MasculineNumberTestHelper(number, expected);
		}

		[Fact]
		public void Ruble0Test()
		{
			var number = 0;
			var expected = "ноль рублей";
			RubleNumberTestHelper(number, expected);
		}

		[Fact]
		public void Masculine1Test()
		{
			var number = 1;
			var expected = "один";
			MasculineNumberTestHelper(number, expected);
		}

		[Fact]
		public void Ruble1Test()
		{
			var number = 1;
			var expected = "один рубль";
			RubleNumberTestHelper(number, expected);
		}

		[Fact]
		public void Masculine2Test()
		{
			var number = 2;
			var expected = "два";
			MasculineNumberTestHelper(number, expected);
		}

		[Fact]
		public void Ruble2Test()
		{
			var number = 2;
			var expected = "два рубля";
			RubleNumberTestHelper(number, expected);
		}

		[Fact]
		public void Masculine3Test()
		{
			var number = 3;
			var expected = "три";
			MasculineNumberTestHelper(number, expected);
		}

		[Fact]
		public void Ruble3Test()
		{
			var number = 3;
			var expected = "три рубля";
			RubleNumberTestHelper(number, expected);
		}

		[Fact]
		public void Masculine4Test()
		{
			var number = 4;
			var expected = "четыре";
			MasculineNumberTestHelper(number, expected);
		}

		[Fact]
		public void Ruble4Test()
		{
			var number = 4;
			var expected = "четыре рубля";
			RubleNumberTestHelper(number, expected);
		}

		[Fact]
		public void Masculine5Test()
		{
			var number = 5;
			var expected = "пять";
			MasculineNumberTestHelper(number, expected);
		}

		[Fact]
		public void Ruble5Test()
		{
			var number = 5;
			var expected = "пять рублей";
			RubleNumberTestHelper(number, expected);
		}

		[Fact]
		public void Masculine6Test()
		{
			var number = 6;
			var expected = "шесть";
			MasculineNumberTestHelper(number, expected);
		}

		[Fact]
		public void Ruble6Test()
		{
			var number = 6;
			var expected = "шесть рублей";
			RubleNumberTestHelper(number, expected);
		}

		[Fact]
		public void Masculine7Test()
		{
			var number = 7;
			var expected = "семь";
			MasculineNumberTestHelper(number, expected);
		}

		[Fact]
		public void Ruble7Test()
		{
			var number = 7;
			var expected = "семь рублей";
			RubleNumberTestHelper(number, expected);
		}

		[Fact]
		public void Masculine8Test()
		{
			var number = 8;
			var expected = "восемь";
			MasculineNumberTestHelper(number, expected);
		}

		[Fact]
		public void Ruble8Test()
		{
			var number = 8;
			var expected = "восемь рублей";
			RubleNumberTestHelper(number, expected);
		}

		[Fact]
		public void Masculine9Test()
		{
			var number = 9;
			var expected = "девять";
			MasculineNumberTestHelper(number, expected);
		}

		[Fact]
		public void Ruble9Test()
		{
			var number = 9;
			var expected = "девять рублей";
			RubleNumberTestHelper(number, expected);
		}

		[Fact]
		public void Masculine10Test()
		{
			var number = 10;
			var expected = "десять";
			MasculineNumberTestHelper(number, expected);
		}

		[Fact]
		public void Ruble10Test()
		{
			var number = 10;
			var expected = "десять рублей";
			RubleNumberTestHelper(number, expected);
		}

		[Fact]
		public void Masculine11Test()
		{
			var number = 11;
			var expected = "одинадцать";
			MasculineNumberTestHelper(number, expected);
		}

		[Fact]
		public void Ruble11Test()
		{
			var number = 11;
			var expected = "одинадцать рублей";
			RubleNumberTestHelper(number, expected);
		}

		[Fact]
		public void Masculine12Test()
		{
			var number = 12;
			var expected = "двенадцать";
			MasculineNumberTestHelper(number, expected);
		}

		[Fact]
		public void Ruble12Test()
		{
			var number = 12;
			var expected = "двенадцать рублей";
			RubleNumberTestHelper(number, expected);
		}

		[Fact]
		public void Masculine13Test()
		{
			var number = 13;
			var expected = "тринадцать";
			MasculineNumberTestHelper(number, expected);
		}

		[Fact]
		public void Ruble13Test()
		{
			var number = 13;
			var expected = "тринадцать рублей";
			RubleNumberTestHelper(number, expected);
		}

		[Fact]
		public void Masculine14Test()
		{
			var number = 14;
			var expected = "четырнадцать";
			MasculineNumberTestHelper(number, expected);
		}

		[Fact]
		public void Ruble14Test()
		{
			var number = 14;
			var expected = "четырнадцать рублей";
			RubleNumberTestHelper(number, expected);
		}

		[Fact]
		public void Masculine15Test()
		{
			var number = 15;
			var expected = "пятнадцать";
			MasculineNumberTestHelper(number, expected);
		}

		[Fact]
		public void Ruble15Test()
		{
			var number = 15;
			var expected = "пятнадцать рублей";
			RubleNumberTestHelper(number, expected);
		}

		[Fact]
		public void Masculine16Test()
		{
			var number = 16;
			var expected = "шестнадцать";
			MasculineNumberTestHelper(number, expected);
		}

		[Fact]
		public void Ruble16Test()
		{
			var number = 16;
			var expected = "шестнадцать рублей";
			RubleNumberTestHelper(number, expected);
		}

		[Fact]
		public void Masculine17Test()
		{
			var number = 17;
			var expected = "семнадцать";
			MasculineNumberTestHelper(number, expected);
		}

		[Fact]
		public void Ruble17Test()
		{
			var number = 17;
			var expected = "семнадцать рублей";
			RubleNumberTestHelper(number, expected);
		}

		[Fact]
		public void Masculine18Test()
		{
			var number = 18;
			var expected = "восемнадцать";
			MasculineNumberTestHelper(number, expected);
		}

		[Fact]
		public void Ruble18Test()
		{
			var number = 18;
			var expected = "восемнадцать рублей";
			RubleNumberTestHelper(number, expected);
		}

		[Fact]
		public void Masculine19Test()
		{
			var number = 19;
			var expected = "девятнадцать";
			MasculineNumberTestHelper(number, expected);
		}

		[Fact]
		public void Ruble19Test()
		{
			var number = 19;
			var expected = "девятнадцать рублей";
			RubleNumberTestHelper(number, expected);
		}

		[Fact]
		public void Masculine20Test()
		{
			var number = 20;
			var expected = "двадцать";
			MasculineNumberTestHelper(number, expected);
		}

		[Fact]
		public void Ruble20Test()
		{
			var number = 20;
			var expected = "двадцать рублей";
			RubleNumberTestHelper(number, expected);
		}

		[Fact]
		public void Masculine25Test()
		{
			var number = 25;
			var expected = "двадцать пять";
			MasculineNumberTestHelper(number, expected);
		}

		[Fact]
		public void Ruble25Test()
		{
			var number = 25;
			var expected = "двадцать пять рублей";
			RubleNumberTestHelper(number, expected);
		}

		[Fact]
		public void Masculine27Test()
		{
			var number = 27;
			var expected = "двадцать семь";
			MasculineNumberTestHelper(number, expected);
		}

		[Fact]
		public void Ruble27Test()
		{
			var number = 27;
			var expected = "двадцать семь рублей";
			RubleNumberTestHelper(number, expected);
		}

		[Fact]
		public void Masculine29Test()
		{
			var number = 29;
			var expected = "двадцать девять";
			MasculineNumberTestHelper(number, expected);
		}

		[Fact]
		public void Ruble29Test()
		{
			var number = 29;
			var expected = "двадцать девять рублей";
			RubleNumberTestHelper(number, expected);
		}

		[Fact]
		public void Masculine30Test()
		{
			var number = 30;
			var expected = "тридцать";
			MasculineNumberTestHelper(number, expected);
		}

		[Fact]
		public void Ruble30Test()
		{
			var number = 30;
			var expected = "тридцать рублей";
			RubleNumberTestHelper(number, expected);
		}

		[Fact]
		public void Masculine31Test()
		{
			var number = 31;
			var expected = "тридцать один";
			MasculineNumberTestHelper(number, expected);
		}

		[Fact]
		public void Ruble31Test()
		{
			var number = 31;
			var expected = "тридцать один рубль";
			RubleNumberTestHelper(number, expected);
		}

		[Fact]
		public void Masculine39Test()
		{
			var number = 39;
			var expected = "тридцать девять";
			MasculineNumberTestHelper(number, expected);
		}

		[Fact]
		public void Ruble39Test()
		{
			var number = 39;
			var expected = "тридцать девять рублей";
			RubleNumberTestHelper(number, expected);
		}

		[Fact]
		public void Masculine40Test()
		{
			var number = 40;
			var expected = "сорок";
			MasculineNumberTestHelper(number, expected);
		}

		[Fact]
		public void Ruble40Test()
		{
			var number = 40;
			var expected = "сорок рублей";
			RubleNumberTestHelper(number, expected);
		}

		[Fact]
		public void Masculine45Test()
		{
			var number = 45;
			var expected = "сорок пять";
			MasculineNumberTestHelper(number, expected);
		}

		[Fact]
		public void Ruble45Test()
		{
			var number = 45;
			var expected = "сорок пять рублей";
			RubleNumberTestHelper(number, expected);
		}

		[Fact]
		public void Masculine50Test()
		{
			var number = 50;
			var expected = "пятьдесят";
			MasculineNumberTestHelper(number, expected);
		}

		[Fact]
		public void Ruble50Test()
		{
			var number = 50;
			var expected = "пятьдесят рублей";
			RubleNumberTestHelper(number, expected);
		}

		[Fact]
		public void Masculine51Test()
		{
			var number = 51;
			var expected = "пятьдесят один";
			MasculineNumberTestHelper(number, expected);
		}

		[Fact]
		public void Ruble51Test()
		{
			var number = 51;
			var expected = "пятьдесят один рубль";
			RubleNumberTestHelper(number, expected);
		}

		[Fact]
		public void Masculine60Test()
		{
			var number = 60;
			var expected = "шестьдесят";
			MasculineNumberTestHelper(number, expected);
		}

		[Fact]
		public void Ruble60Test()
		{
			var number = 60;
			var expected = "шестьдесят рублей";
			RubleNumberTestHelper(number, expected);
		}

		[Fact]
		public void Masculine68Test()
		{
			var number = 68;
			var expected = "шестьдесят восемь";
			MasculineNumberTestHelper(number, expected);
		}

		[Fact]
		public void Ruble68Test()
		{
			var number = 68;
			var expected = "шестьдесят восемь рублей";
			RubleNumberTestHelper(number, expected);
		}

		[Fact]
		public void Masculine70Test()
		{
			var number = 70;
			var expected = "семьдесят";
			MasculineNumberTestHelper(number, expected);
		}

		[Fact]
		public void Ruble70Test()
		{
			var number = 70;
			var expected = "семьдесят рублей";
			RubleNumberTestHelper(number, expected);
		}

		[Fact]
		public void Masculine77Test()
		{
			var number = 77;
			var expected = "семьдесят семь";
			MasculineNumberTestHelper(number, expected);
		}

		[Fact]
		public void Ruble77Test()
		{
			var number = 77;
			var expected = "семьдесят семь рублей";
			RubleNumberTestHelper(number, expected);
		}

		[Fact]
		public void Masculine80Test()
		{
			var number = 80;
			var expected = "восемьдесят";
			MasculineNumberTestHelper(number, expected);
		}

		[Fact]
		public void Ruble80Test()
		{
			var number = 80;
			var expected = "восемьдесят рублей";
			RubleNumberTestHelper(number, expected);
		}

		[Fact]
		public void Masculine81Test()
		{
			var number = 81;
			var expected = "восемьдесят один";
			MasculineNumberTestHelper(number, expected);
		}

		[Fact]
		public void Ruble81Test()
		{
			var number = 81;
			var expected = "восемьдесят один рубль";
			RubleNumberTestHelper(number, expected);
		}

		[Fact]
		public void Masculine90Test()
		{
			var number = 90;
			var expected = "девяносто";
			MasculineNumberTestHelper(number, expected);
		}

		[Fact]
		public void Ruble90Test()
		{
			var number = 90;
			var expected = "девяносто рублей";
			RubleNumberTestHelper(number, expected);
		}

		[Fact]
		public void Masculine99Test()
		{
			var number = 99;
			var expected = "девяносто девять";
			MasculineNumberTestHelper(number, expected);
		}

		[Fact]
		public void Ruble99Test()
		{
			var number = 99;
			var expected = "девяносто девять рублей";
			RubleNumberTestHelper(number, expected);
		}

		[Fact]
		public void Masculine100Test()
		{
			var number = 100;
			var expected = "сто";
			MasculineNumberTestHelper(number, expected);
		}

		[Fact]
		public void Ruble100Test()
		{
			var number = 100;
			var expected = "сто рублей";
			RubleNumberTestHelper(number, expected);
		}

		[Fact]
		public void Masculine101Test()
		{
			var number = 101;
			var expected = "сто один";
			MasculineNumberTestHelper(number, expected);
		}

		[Fact]
		public void Ruble101Test()
		{
			var number = 101;
			var expected = "сто один рубль";
			RubleNumberTestHelper(number, expected);
		}

		[Fact]
		public void Masculine115Test()
		{
			var number = 115;
			var expected = "сто пятнадцать";
			MasculineNumberTestHelper(number, expected);
		}

		[Fact]
		public void Ruble115Test()
		{
			var number = 115;
			var expected = "сто пятнадцать рублей";
			RubleNumberTestHelper(number, expected);
		}

		[Fact]
		public void Masculine120Test()
		{
			var number = 120;
			var expected = "сто двадцать";
			MasculineNumberTestHelper(number, expected);
		}

		[Fact]
		public void Ruble120Test()
		{
			var number = 120;
			var expected = "сто двадцать рублей";
			RubleNumberTestHelper(number, expected);
		}

		[Fact]
		public void Masculine150Test()
		{
			var number = 150;
			var expected = "сто пятьдесят";
			MasculineNumberTestHelper(number, expected);
		}

		[Fact]
		public void Ruble150Test()
		{
			var number = 150;
			var expected = "сто пятьдесят рублей";
			RubleNumberTestHelper(number, expected);
		}

		[Fact]
		public void Masculine155Test()
		{
			var number = 155;
			var expected = "сто пятьдесят пять";
			MasculineNumberTestHelper(number, expected);
		}

		[Fact]
		public void Ruble155Test()
		{
			var number = 155;
			var expected = "сто пятьдесят пять рублей";
			RubleNumberTestHelper(number, expected);
		}

		[Fact]
		public void Masculine199Test()
		{
			var number = 199;
			var expected = "сто девяносто девять";
			MasculineNumberTestHelper(number, expected);
		}

		[Fact]
		public void Ruble199Test()
		{
			var number = 199;
			var expected = "сто девяносто девять рублей";
			RubleNumberTestHelper(number, expected);
		}

		[Fact]
		public void Masculine200Test()
		{
			var number = 200;
			var expected = "двести";
			MasculineNumberTestHelper(number, expected);
		}

		[Fact]
		public void Ruble200Test()
		{
			var number = 200;
			var expected = "двести рублей";
			RubleNumberTestHelper(number, expected);
		}

		[Fact]
		public void Masculine201Test()
		{
			var number = 201;
			var expected = "двести один";
			MasculineNumberTestHelper(number, expected);
		}

		[Fact]
		public void Ruble201Test()
		{
			var number = 201;
			var expected = "двести один рубль";
			RubleNumberTestHelper(number, expected);
		}

		[Fact]
		public void Masculine220Test()
		{
			var number = 220;
			var expected = "двести двадцать";
			MasculineNumberTestHelper(number, expected);
		}

		[Fact]
		public void Ruble220Test()
		{
			var number = 220;
			var expected = "двести двадцать рублей";
			RubleNumberTestHelper(number, expected);
		}

		[Fact]
		public void Masculine300Test()
		{
			var number = 300;
			var expected = "триста";
			MasculineNumberTestHelper(number, expected);
		}

		[Fact]
		public void Ruble300Test()
		{
			var number = 300;
			var expected = "триста рублей";
			RubleNumberTestHelper(number, expected);
		}

		[Fact]
		public void Masculine301Test()
		{
			var number = 301;
			var expected = "триста один";
			MasculineNumberTestHelper(number, expected);
		}

		[Fact]
		public void Ruble301Test()
		{
			var number = 301;
			var expected = "триста один рубль";
			RubleNumberTestHelper(number, expected);
		}

		[Fact]
		public void Masculine357Test()
		{
			var number = 357;
			var expected = "триста пятьдесят семь";
			MasculineNumberTestHelper(number, expected);
		}

		[Fact]
		public void Ruble357Test()
		{
			var number = 357;
			var expected = "триста пятьдесят семь рублей";
			RubleNumberTestHelper(number, expected);
		}

		[Fact]
		public void Masculine399Test()
		{
			var number = 399;
			var expected = "триста девяносто девять";
			MasculineNumberTestHelper(number, expected);
		}

		[Fact]
		public void Ruble399Test()
		{
			var number = 399;
			var expected = "триста девяносто девять рублей";
			RubleNumberTestHelper(number, expected);
		}

		[Fact]
		public void Masculine400Test()
		{
			var number = 400;
			var expected = "четыреста";
			MasculineNumberTestHelper(number, expected);
		}

		[Fact]
		public void Ruble400Test()
		{
			var number = 400;
			var expected = "четыреста рублей";
			RubleNumberTestHelper(number, expected);
		}

		[Fact]
		public void Masculine401Test()
		{
			var number = 401;
			var expected = "четыреста один";
			MasculineNumberTestHelper(number, expected);
		}

		[Fact]
		public void Ruble401Test()
		{
			var number = 401;
			var expected = "четыреста один рубль";
			RubleNumberTestHelper(number, expected);
		}

		[Fact]
		public void Masculine499Test()
		{
			var number = 499;
			var expected = "четыреста девяносто девять";
			MasculineNumberTestHelper(number, expected);
		}

		[Fact]
		public void Ruble499Test()
		{
			var number = 499;
			var expected = "четыреста девяносто девять рублей";
			RubleNumberTestHelper(number, expected);
		}

		[Fact]
		public void Masculine500Test()
		{
			var number = 500;
			var expected = "пятьсот";
			MasculineNumberTestHelper(number, expected);
		}

		[Fact]
		public void Ruble500Test()
		{
			var number = 500;
			var expected = "пятьсот рублей";
			RubleNumberTestHelper(number, expected);
		}

		[Fact]
		public void Masculine501Test()
		{
			var number = 501;
			var expected = "пятьсот один";
			MasculineNumberTestHelper(number, expected);
		}

		[Fact]
		public void Ruble501Test()
		{
			var number = 501;
			var expected = "пятьсот один рубль";
			RubleNumberTestHelper(number, expected);
		}

		[Fact]
		public void Masculine599Test()
		{
			var number = 599;
			var expected = "пятьсот девяносто девять";
			MasculineNumberTestHelper(number, expected);
		}

		[Fact]
		public void Ruble599Test()
		{
			var number = 599;
			var expected = "пятьсот девяносто девять рублей";
			RubleNumberTestHelper(number, expected);
		}

		[Fact]
		public void Masculine600Test()
		{
			var number = 600;
			var expected = "шестьсот";
			MasculineNumberTestHelper(number, expected);
		}

		[Fact]
		public void Ruble600Test()
		{
			var number = 600;
			var expected = "шестьсот рублей";
			RubleNumberTestHelper(number, expected);
		}

		[Fact]
		public void Masculine601Test()
		{
			var number = 601;
			var expected = "шестьсот один";
			MasculineNumberTestHelper(number, expected);
		}

		[Fact]
		public void Ruble601Test()
		{
			var number = 601;
			var expected = "шестьсот один рубль";
			RubleNumberTestHelper(number, expected);
		}

		[Fact]
		public void Masculine700Test()
		{
			var number = 700;
			var expected = "семьсот";
			MasculineNumberTestHelper(number, expected);
		}

		[Fact]
		public void Ruble700Test()
		{
			var number = 700;
			var expected = "семьсот рублей";
			RubleNumberTestHelper(number, expected);
		}

		[Fact]
		public void Masculine800Test()
		{
			var number = 800;
			var expected = "восемьсот";
			MasculineNumberTestHelper(number, expected);
		}

		[Fact]
		public void Ruble800Test()
		{
			var number = 800;
			var expected = "восемьсот рублей";
			RubleNumberTestHelper(number, expected);
		}

		[Fact]
		public void Masculine900Test()
		{
			var number = 900;
			var expected = "девятьсот";
			MasculineNumberTestHelper(number, expected);
		}

		[Fact]
		public void Ruble900Test()
		{
			var number = 900;
			var expected = "девятьсот рублей";
			RubleNumberTestHelper(number, expected);
		}

		[Fact]
		public void Masculine999Test()
		{
			var number = 999;
			var expected = "девятьсот девяносто девять";
			MasculineNumberTestHelper(number, expected);
		}

		[Fact]
		public void Ruble999Test()
		{
			var number = 999;
			var expected = "девятьсот девяносто девять рублей";
			RubleNumberTestHelper(number, expected);
		}

		[Fact]
		public void Masculine1000Test()
		{
			var number = 1000;
			var expected = "одна тысяча";
			MasculineNumberTestHelper(number, expected);
		}

		[Fact]
		public void Ruble1000Test()
		{
			var number = 1000;
			var expected = "одна тысяча рублей";
			RubleNumberTestHelper(number, expected);
		}

		[Fact]
		public void Masculine1001Test()
		{
			var number = 1001;
			var expected = "одна тысяча один";
			MasculineNumberTestHelper(number, expected);
		}

		[Fact]
		public void Ruble1001Test()
		{
			var number = 1001;
			var expected = "одна тысяча один рубль";
			RubleNumberTestHelper(number, expected);
		}

		[Fact]
		public void Masculine1010Test()
		{
			var number = 1010;
			var expected = "одна тысяча десять";
			MasculineNumberTestHelper(number, expected);
		}

		[Fact]
		public void Ruble1010Test()
		{
			var number = 1010;
			var expected = "одна тысяча десять рублей";
			RubleNumberTestHelper(number, expected);
		}

		[Fact]
		public void Masculine1015Test()
		{
			var number = 1015;
			var expected = "одна тысяча пятнадцать";
			MasculineNumberTestHelper(number, expected);
		}

		[Fact]
		public void Ruble1015Test()
		{
			var number = 1015;
			var expected = "одна тысяча пятнадцать рублей";
			RubleNumberTestHelper(number, expected);
		}

		[Fact]
		public void Masculine1100Test()
		{
			var number = 1100;
			var expected = "одна тысяча сто";
			MasculineNumberTestHelper(number, expected);
		}

		[Fact]
		public void Ruble1100Test()
		{
			var number = 1100;
			var expected = "одна тысяча сто рублей";
			RubleNumberTestHelper(number, expected);
		}

		[Fact]
		public void Masculine1206Test()
		{
			var number = 1206;
			var expected = "одна тысяча двести шесть";
			MasculineNumberTestHelper(number, expected);
		}

		[Fact]
		public void Ruble1206Test()
		{
			var number = 1206;
			var expected = "одна тысяча двести шесть рублей";
			RubleNumberTestHelper(number, expected);
		}

		[Fact]
		public void Masculine1220Test()
		{
			var number = 1220;
			var expected = "одна тысяча двести двадцать";
			MasculineNumberTestHelper(number, expected);
		}

		[Fact]
		public void Ruble1220Test()
		{
			var number = 1220;
			var expected = "одна тысяча двести двадцать рублей";
			RubleNumberTestHelper(number, expected);
		}

		[Fact]
		public void Masculine1399Test()
		{
			var number = 1399;
			var expected = "одна тысяча триста девяносто девять";
			MasculineNumberTestHelper(number, expected);
		}

		[Fact]
		public void Ruble1399Test()
		{
			var number = 1399;
			var expected = "одна тысяча триста девяносто девять рублей";
			RubleNumberTestHelper(number, expected);
		}

		[Fact]
		public void Masculine1500Test()
		{
			var number = 1500;
			var expected = "одна тысяча пятьсот";
			MasculineNumberTestHelper(number, expected);
		}

		[Fact]
		public void Ruble1500Test()
		{
			var number = 1500;
			var expected = "одна тысяча пятьсот рублей";
			RubleNumberTestHelper(number, expected);
		}

		[Fact]
		public void Masculine1999Test()
		{
			var number = 1999;
			var expected = "одна тысяча девятьсот девяносто девять";
			MasculineNumberTestHelper(number, expected);
		}

		[Fact]
		public void Ruble1999Test()
		{
			var number = 1999;
			var expected = "одна тысяча девятьсот девяносто девять рублей";
			RubleNumberTestHelper(number, expected);
		}

		[Fact]
		public void Masculine2000Test()
		{
			var number = 2000;
			var expected = "две тысячи";
			MasculineNumberTestHelper(number, expected);
		}

		[Fact]
		public void Ruble2000Test()
		{
			var number = 2000;
			var expected = "две тысячи рублей";
			RubleNumberTestHelper(number, expected);
		}

		[Fact]
		public void Masculine3000Test()
		{
			var number = 3000;
			var expected = "три тысячи";
			MasculineNumberTestHelper(number, expected);
		}

		[Fact]
		public void Ruble3000Test()
		{
			var number = 3000;
			var expected = "три тысячи рублей";
			RubleNumberTestHelper(number, expected);
		}

		[Fact]
		public void Masculine4000Test()
		{
			var number = 4000;
			var expected = "четыре тысячи";
			MasculineNumberTestHelper(number, expected);
		}

		[Fact]
		public void Ruble4000Test()
		{
			var number = 4000;
			var expected = "четыре тысячи рублей";
			RubleNumberTestHelper(number, expected);
		}

		[Fact]
		public void Masculine10000Test()
		{
			var number = 10000;
			var expected = "десять тысяч";
			MasculineNumberTestHelper(number, expected);
		}

		[Fact]
		public void Ruble10000Test()
		{
			var number = 10000;
			var expected = "десять тысяч рублей";
			RubleNumberTestHelper(number, expected);
		}

		[Fact]
		public void Masculine81818Test()
		{
			var number = 81818;
			var expected = "восемьдесят одна тысяча восемьсот восемнадцать";
			MasculineNumberTestHelper(number, expected);
		}

		[Fact]
		public void Ruble81818Test()
		{
			var number = 81818;
			var expected = "восемьдесят одна тысяча восемьсот восемнадцать рублей";
			RubleNumberTestHelper(number, expected);
		}

		[Fact]
		public void Masculine99999Test()
		{
			var number = 99999;
			var expected = "девяносто девять тысяч девятьсот девяносто девять";
			MasculineNumberTestHelper(number, expected);
		}

		[Fact]
		public void Ruble99999Test()
		{
			var number = 99999;
			var expected = "девяносто девять тысяч девятьсот девяносто девять рублей";
			RubleNumberTestHelper(number, expected);
		}

		[Fact]
		public void Masculine100000Test()
		{
			var number = 100000;
			var expected = "сто тысяч";
			MasculineNumberTestHelper(number, expected);
		}

		[Fact]
		public void Ruble100000Test()
		{
			var number = 100000;
			var expected = "сто тысяч рублей";
			RubleNumberTestHelper(number, expected);
		}

		[Fact]
		public void Masculine100001Test()
		{
			var number = 100001;
			var expected = "сто тысяч один";
			MasculineNumberTestHelper(number, expected);
		}

		[Fact]
		public void Ruble100001Test()
		{
			var number = 100001;
			var expected = "сто тысяч один рубль";
			RubleNumberTestHelper(number, expected);
		}

		[Fact]
		public void Masculine110000Test()
		{
			var number = 110000;
			var expected = "сто десять тысяч";
			MasculineNumberTestHelper(number, expected);
		}

		[Fact]
		public void Ruble110000Test()
		{
			var number = 110000;
			var expected = "сто десять тысяч рублей";
			RubleNumberTestHelper(number, expected);
		}

		[Fact]
		public void Masculine156945Test()
		{
			var number = 156945;
			var expected = "сто пятьдесят шесть тысяч девятьсот сорок пять";
			MasculineNumberTestHelper(number, expected);
		}

		[Fact]
		public void Ruble156945Test()
		{
			var number = 156945;
			var expected = "сто пятьдесят шесть тысяч девятьсот сорок пять рублей";
			RubleNumberTestHelper(number, expected);
		}

		[Fact]
		public void Masculine299999Test()
		{
			var number = 299999;
			var expected = "двести девяносто девять тысяч девятьсот девяносто девять";
			MasculineNumberTestHelper(number, expected);
		}

		[Fact]
		public void Ruble299999Test()
		{
			var number = 299999;
			var expected = "двести девяносто девять тысяч девятьсот девяносто девять рублей";
			RubleNumberTestHelper(number, expected);
		}

		[Fact]
		public void Masculine999999Test()
		{
			var number = 999999;
			var expected = "девятьсот девяносто девять тысяч девятьсот девяносто девять";
			MasculineNumberTestHelper(number, expected);
		}

		[Fact]
		public void Ruble999999Test()
		{
			var number = 999999;
			var expected = "девятьсот девяносто девять тысяч девятьсот девяносто девять рублей";
			RubleNumberTestHelper(number, expected);
		}

		[Fact]
		public void Masculine1000000Test()
		{
			var number = 1000000;
			var expected = "один миллион";
			MasculineNumberTestHelper(number, expected);
		}

		[Fact]
		public void Ruble1000000Test()
		{
			var number = 1000000;
			var expected = "один миллион рублей";
			RubleNumberTestHelper(number, expected);
		}

		[Fact]
		public void Masculine1000001Test()
		{
			var number = 1000001;
			var expected = "один миллион один";
			MasculineNumberTestHelper(number, expected);
		}

		[Fact]
		public void Ruble1000001Test()
		{
			var number = 1000001;
			var expected = "один миллион один рубль";
			RubleNumberTestHelper(number, expected);
		}

		[Fact]
		public void Masculine1000010Test()
		{
			var number = 1000010;
			var expected = "один миллион десять";
			MasculineNumberTestHelper(number, expected);
		}

		[Fact]
		public void Ruble1000010Test()
		{
			var number = 1000010;
			var expected = "один миллион десять рублей";
			RubleNumberTestHelper(number, expected);
		}

		[Fact]
		public void Masculine1000200Test()
		{
			var number = 1000200;
			var expected = "один миллион двести";
			MasculineNumberTestHelper(number, expected);
		}

		[Fact]
		public void Ruble1000200Test()
		{
			var number = 1000200;
			var expected = "один миллион двести рублей";
			RubleNumberTestHelper(number, expected);
		}

		[Fact]
		public void Masculine1003000Test()
		{
			var number = 1003000;
			var expected = "один миллион три тысячи";
			MasculineNumberTestHelper(number, expected);
		}

		[Fact]
		public void Ruble1003000Test()
		{
			var number = 1003000;
			var expected = "один миллион три тысячи рублей";
			RubleNumberTestHelper(number, expected);
		}

		[Fact]
		public void Masculine1053000Test()
		{
			var number = 1053000;
			var expected = "один миллион пятьдесят три тысячи";
			MasculineNumberTestHelper(number, expected);
		}

		[Fact]
		public void Ruble1053000Test()
		{
			var number = 1053000;
			var expected = "один миллион пятьдесят три тысячи рублей";
			RubleNumberTestHelper(number, expected);
		}

		[Fact]
		public void Masculine1234567Test()
		{
			var number = 1234567;
			var expected = "один миллион двести тридцать четыре тысячи пятьсот шестьдесят семь";
			MasculineNumberTestHelper(number, expected);
		}

		[Fact]
		public void Ruble1234567Test()
		{
			var number = 1234567;
			var expected = "один миллион двести тридцать четыре тысячи пятьсот шестьдесят семь рублей";
			RubleNumberTestHelper(number, expected);
		}

		[Fact]
		public void Masculine50000000Test()
		{
			var number = 50000000;
			var expected = "пятьдесят миллионов";
			MasculineNumberTestHelper(number, expected);
		}

		[Fact]
		public void Ruble50000000Test()
		{
			var number = 50000000;
			var expected = "пятьдесят миллионов рублей";
			RubleNumberTestHelper(number, expected);
		}

		[Fact]
		public void Masculine54568481Test()
		{
			var number = 54568481;
			var expected = "пятьдесят четыре миллиона пятьсот шестьдесят восемь тысяч четыреста восемьдесят один";
			MasculineNumberTestHelper(number, expected);
		}

		[Fact]
		public void Ruble54568481Test()
		{
			var number = 54568481;
			var expected = "пятьдесят четыре миллиона пятьсот шестьдесят восемь тысяч четыреста восемьдесят один рубль";
			RubleNumberTestHelper(number, expected);
		}

		[Fact]
		public void Masculine999999999Test()
		{
			var number = 999999999;
			var expected = "девятьсот девяносто девять миллионов девятьсот девяносто девять тысяч девятьсот девяносто девять";
			MasculineNumberTestHelper(number, expected);
		}

		[Fact]
		public void Ruble999999999Test()
		{
			var number = 999999999;
			var expected = "девятьсот девяносто девять миллионов девятьсот девяносто девять тысяч девятьсот девяносто девять рублей";
			RubleNumberTestHelper(number, expected);
		}

		[Fact]
		public void MasculineMinus1Test()
		{
			var number = -1;
			var expected = "минус один";
			MasculineNumberTestHelper(number, expected);
		}

		[Fact]
		public void RubleMinus1Test()
		{
			var number = -1;
			var expected = "минус один рубль";
			RubleNumberTestHelper(number, expected);
		}

		[Fact]
		public void MasculineMinus7Test()
		{
			var number = -7;
			var expected = "минус семь";
			MasculineNumberTestHelper(number, expected);
		}

		[Fact]
		public void RubleMinus7Test()
		{
			var number = -7;
			var expected = "минус семь рублей";
			RubleNumberTestHelper(number, expected);
		}

		[Fact]
		public void MasculineMinus10Test()
		{
			var number = -10;
			var expected = "минус десять";
			MasculineNumberTestHelper(number, expected);
		}

		[Fact]
		public void RubleMinus10Test()
		{
			var number = -10;
			var expected = "минус десять рублей";
			RubleNumberTestHelper(number, expected);
		}

		[Fact]
		public void MasculineMinus11Test()
		{
			var number = -11;
			var expected = "минус одинадцать";
			MasculineNumberTestHelper(number, expected);
		}

		[Fact]
		public void RubleMinus11Test()
		{
			var number = -11;
			var expected = "минус одинадцать рублей";
			RubleNumberTestHelper(number, expected);
		}

		[Fact]
		public void MasculineMinus40Test()
		{
			var number = -40;
			var expected = "минус сорок";
			MasculineNumberTestHelper(number, expected);
		}

		[Fact]
		public void RubleMinus40Test()
		{
			var number = -40;
			var expected = "минус сорок рублей";
			RubleNumberTestHelper(number, expected);
		}

		[Fact]
		public void MasculineMinus99Test()
		{
			var number = -99;
			var expected = "минус девяносто девять";
			MasculineNumberTestHelper(number, expected);
		}

		[Fact]
		public void RubleMinus99Test()
		{
			var number = -99;
			var expected = "минус девяносто девять рублей";
			RubleNumberTestHelper(number, expected);
		}

		[Fact]
		public void MasculineMinus100Test()
		{
			var number = -100;
			var expected = "минус сто";
			MasculineNumberTestHelper(number, expected);
		}

		[Fact]
		public void RubleMinus100Test()
		{
			var number = -100;
			var expected = "минус сто рублей";
			RubleNumberTestHelper(number, expected);
		}

		[Fact]
		public void MasculineMinus101Test()
		{
			var number = -101;
			var expected = "минус сто один";
			MasculineNumberTestHelper(number, expected);
		}

		[Fact]
		public void RubleMinus101Test()
		{
			var number = -101;
			var expected = "минус сто один рубль";
			RubleNumberTestHelper(number, expected);
		}

		[Fact]
		public void MasculineMinus220Test()
		{
			var number = -220;
			var expected = "минус двести двадцать";
			MasculineNumberTestHelper(number, expected);
		}

		[Fact]
		public void RubleMinus220Test()
		{
			var number = -220;
			var expected = "минус двести двадцать рублей";
			RubleNumberTestHelper(number, expected);
		}

		[Fact]
		public void MasculineMinus300Test()
		{
			var number = -300;
			var expected = "минус триста";
			MasculineNumberTestHelper(number, expected);
		}

		[Fact]
		public void RubleMinus300Test()
		{
			var number = -300;
			var expected = "минус триста рублей";
			RubleNumberTestHelper(number, expected);
		}

	}
}

